# =============================================================================
# setup.ps1 — VulnLab Quickstart: one-time setup for Windows
#
# What this script does:
#   1. Detects the repo root automatically (no hardcoded paths)
#   2. Generates .env files for lab-api and webapp
#   3. Installs Node.js dependencies (npm install) for both projects
#   4. Pulls and starts all Docker lab containers (docker compose up -d)
#   5. Starts the backend Lab API server on port 4100
#   6. Starts the Next.js web dashboard on port 3000
#
# Usage (first time):
#   cd <repo-root>
#   PowerShell -ExecutionPolicy Bypass -File .\setup.ps1
#
# Usage (subsequent runs — just starts the servers):
#   .\setup.ps1
# =============================================================================

$ErrorActionPreference = "Stop"

# ── Auto-detect repo root ─────────────────────────────────────────────────────
$RepoRoot  = $PSScriptRoot          # always the folder this script lives in
$LabApiDir = Join-Path $RepoRoot "lab-api"
$WebappDir = Join-Path $RepoRoot "webapp"

Write-Host ""
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  VulnLab Quickstart — Setup" -ForegroundColor Cyan
Write-Host "  Repo root : $RepoRoot" -ForegroundColor Gray
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host ""

# ── 1. Preflight checks ───────────────────────────────────────────────────────
Write-Host "[CHECK] Verifying prerequisites..." -ForegroundColor Yellow

if (-not (Get-Command "node" -ErrorAction SilentlyContinue)) {
    Write-Host "  ERROR: Node.js not found. Install from https://nodejs.org" -ForegroundColor Red; exit 1
}
if (-not (Get-Command "npm" -ErrorAction SilentlyContinue)) {
    Write-Host "  ERROR: npm not found. Install Node.js from https://nodejs.org" -ForegroundColor Red; exit 1
}
if (-not (Get-Command "docker" -ErrorAction SilentlyContinue)) {
    Write-Host "  ERROR: Docker not found. Install Docker Desktop from https://docker.com" -ForegroundColor Red; exit 1
}

Write-Host "  Node   : $(node --version)" -ForegroundColor Green
Write-Host "  npm    : $(npm --version)" -ForegroundColor Green
Write-Host "  Docker : $(docker --version)" -ForegroundColor Green
Write-Host ""

# ── 2. Generate lab-api/.env from .env.example if missing ────────────────────
$LabEnvFile = Join-Path $LabApiDir ".env"
if (-not (Test-Path $LabEnvFile)) {
    Write-Host "[SETUP] Creating lab-api/.env ..." -ForegroundColor Yellow
    $LabEnvExample = Join-Path $LabApiDir ".env.example"
    if (Test-Path $LabEnvExample) {
        Copy-Item $LabEnvExample $LabEnvFile
    } else {
        @"
# Auto-generated by setup.ps1
API_SECRET=changeme_use_a_strong_random_string
LAB_DIR=
PORT=4100
"@ | Set-Content $LabEnvFile
    }
    Write-Host "  lab-api/.env created (LAB_DIR is blank = auto-detect)" -ForegroundColor Green
} else {
    Write-Host "[SETUP] lab-api/.env already exists — skipping." -ForegroundColor Gray
}

# ── 3. Generate webapp/.env.local if missing ──────────────────────────────────
$WebEnvFile = Join-Path $WebappDir ".env.local"
if (-not (Test-Path $WebEnvFile)) {
    Write-Host "[SETUP] Creating webapp/.env.local ..." -ForegroundColor Yellow
    @"
# Auto-generated by setup.ps1
# Leave NEXT_PUBLIC_LAB_API_URL blank — the Next.js rewrite will proxy /api automatically.
NEXT_PUBLIC_LAB_API_URL=
NEXT_PUBLIC_API_SECRET=changeme_use_a_strong_random_string
LAB_API_PORT=4100
"@ | Set-Content $WebEnvFile
    Write-Host "  webapp/.env.local created" -ForegroundColor Green
} else {
    Write-Host "[SETUP] webapp/.env.local already exists — skipping." -ForegroundColor Gray
}
Write-Host ""

# ── 4. npm install ────────────────────────────────────────────────────────────
Write-Host "[INSTALL] Installing lab-api dependencies..." -ForegroundColor Yellow
Set-Location $LabApiDir
npm install --silent
Write-Host "  Done." -ForegroundColor Green

Write-Host "[INSTALL] Installing webapp dependencies..." -ForegroundColor Yellow
Set-Location $WebappDir
npm install --silent
Write-Host "  Done." -ForegroundColor Green
Write-Host ""

# ── 5. Start Docker containers ────────────────────────────────────────────────
Write-Host "[DOCKER] Starting all lab containers (this may take several minutes on first run)..." -ForegroundColor Yellow
Set-Location $RepoRoot
docker compose up -d
Write-Host "  All containers started." -ForegroundColor Green
Write-Host ""

# ── 6. Free ports 4100 and 3000 if occupied ───────────────────────────────────
@(4100, 3000) | ForEach-Object {
    $conn = Get-NetTCPConnection -LocalPort $_ -State Listen -ErrorAction SilentlyContinue
    if ($conn) {
        Write-Host "[CLEAN] Port $_ in use. Stopping existing process (PID $($conn.OwningProcess))..." -ForegroundColor Yellow
        Stop-Process -Id $conn.OwningProcess -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 1
    }
}

# ── 7. Start Lab API server ───────────────────────────────────────────────────
Write-Host "[START] Starting Lab API backend (port 4100)..." -ForegroundColor Yellow
Set-Location $LabApiDir
$ApiProcess = Start-Process -FilePath "node" -ArgumentList "server.js" `
    -PassThru -NoNewWindow -WorkingDirectory $LabApiDir
Start-Sleep -Seconds 2

# Check Docker and create network
try {
    $null = docker info 2>&1
    if ($LASTEXITCODE -ne 0) { throw "Docker not running" }
    Write-Host "[OK] Docker is running." -ForegroundColor Green
    $null = docker network create lab_net 2>&1
} catch {
    Write-Host "[ERROR] Docker is not running or not installed." -ForegroundColor Red
    exit 1
}

try {
    Invoke-WebRequest -Uri "http://localhost:4100/api/health" -UseBasicParsing -ErrorAction Stop | Out-Null
    Write-Host "  Lab API is UP (PID: $($ApiProcess.Id))" -ForegroundColor Green
} catch {
    Write-Host "  ERROR: Lab API didn't start. Check node server.js output." -ForegroundColor Red
    Stop-Process -Id $ApiProcess.Id -Force -ErrorAction SilentlyContinue
    exit 1
}

# ── 8. Start Next.js webapp ───────────────────────────────────────────────────
Write-Host "[START] Starting Web Dashboard (port 3000)..." -ForegroundColor Yellow
Set-Location $WebappDir
$WebProcess = Start-Process -FilePath "cmd.exe" `
    -ArgumentList "/c npm run dev" `
    -PassThru -NoNewWindow -WorkingDirectory $WebappDir
Start-Sleep -Seconds 5

# ── 9. Done ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "==========================================================" -ForegroundColor Green
Write-Host "  VulnLab is RUNNING!" -ForegroundColor Green
Write-Host ""
Write-Host "  Open the dashboard in your browser:" -ForegroundColor White
Write-Host "    --> http://localhost:3000 <--" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Lab containers accessible at their ports:" -ForegroundColor White
Write-Host "    DVWA        -> http://localhost:8088" -ForegroundColor Gray
Write-Host "    Juice Shop  -> http://localhost:3001" -ForegroundColor Gray
Write-Host "    WebGoat     -> http://localhost:8085" -ForegroundColor Gray
Write-Host "    bWAPP       -> http://localhost:8082" -ForegroundColor Gray
Write-Host "    phpMyAdmin  -> http://localhost:8084" -ForegroundColor Gray
Write-Host ""
Write-Host "  Press Ctrl+C in this window to stop everything." -ForegroundColor Yellow
Write-Host "==========================================================" -ForegroundColor Green
Write-Host ""

# ── Keep alive — wait for API process ────────────────────────────────────────
try {
    Wait-Process -Id $ApiProcess.Id
} finally {
    Write-Host "Shutting down..." -ForegroundColor Yellow
    if ($ApiProcess) { Stop-Process -Id $ApiProcess.Id -Force -ErrorAction SilentlyContinue }
    if ($WebProcess)  { Stop-Process -Id $WebProcess.Id  -Force -ErrorAction SilentlyContinue }
    Write-Host "All processes stopped." -ForegroundColor Gray
}
