#!/usr/bin/env bash
# =============================================================================
# setup.sh — VulnLab Quickstart for Linux / macOS
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
# =============================================================================

set -euo pipefail

# ── Auto-detect repo root (the folder this script lives in) ──────────────────
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_API_DIR="$REPO_ROOT/lab-api"
WEBAPP_DIR="$REPO_ROOT/webapp"

echo ""
echo "=========================================================="
echo "  VulnLab Quickstart — Setup"
echo "  Repo root : $REPO_ROOT"
echo "=========================================================="
echo ""

# ── 1. Preflight checks ───────────────────────────────────────────────────────
echo "[CHECK] Verifying prerequisites..."

command -v node   &>/dev/null || { echo "  ERROR: Node.js not found. Install from https://nodejs.org"; exit 1; }
command -v npm    &>/dev/null || { echo "  ERROR: npm not found. Install Node.js from https://nodejs.org"; exit 1; }
command -v docker &>/dev/null || { echo "  ERROR: Docker not found. Install Docker Desktop from https://docker.com"; exit 1; }

echo "  Node   : $(node --version)"
echo "  npm    : $(npm --version)"
echo "  Docker : $(docker --version)"
echo ""

# ── 2. lab-api/.env ───────────────────────────────────────────────────────────
LAB_ENV="$LAB_API_DIR/.env"
if [ ! -f "$LAB_ENV" ]; then
    echo "[SETUP] Creating lab-api/.env ..."
    if [ -f "$LAB_API_DIR/.env.example" ]; then
        cp "$LAB_API_DIR/.env.example" "$LAB_ENV"
    else
        cat > "$LAB_ENV" <<EOF
# Auto-generated by setup.sh
PORT=4100
LAB_DIR=
EOF
    fi
    echo "  lab-api/.env created (LAB_DIR blank = auto-detect)"
else
    echo "[SETUP] lab-api/.env already exists — skipping."
fi

# ── 3. webapp/.env.local ──────────────────────────────────────────────────────
WEB_ENV="$WEBAPP_DIR/.env.local"
if [ ! -f "$WEB_ENV" ]; then
    echo "[SETUP] Creating webapp/.env.local ..."
    cat > "$WEB_ENV" <<EOF
# Auto-generated by setup.sh
# Leave blank — Next.js rewrites proxy /api/* to the Lab API automatically.
NEXT_PUBLIC_LAB_API_URL=
LAB_API_PORT=4100
EOF
    echo "  webapp/.env.local created."
else
    echo "[SETUP] webapp/.env.local already exists — skipping."
fi
echo ""

# ── 4. npm install ────────────────────────────────────────────────────────────
echo "[INSTALL] Installing lab-api dependencies..."
( cd "$LAB_API_DIR" && npm install --silent )
echo "  Done."

echo "[INSTALL] Installing webapp dependencies..."
( cd "$WEBAPP_DIR" && npm install --silent )
echo "  Done."
echo ""

# ── 5. Docker containers ──────────────────────────────────────────────────────
echo "[DOCKER] Starting all lab containers (may take several minutes on first run)..."
( cd "$REPO_ROOT" && docker compose up -d )
echo "  All containers started."
echo ""

# ── 6. Free occupied ports ────────────────────────────────────────────────────
for PORT_NUM in 4100 3000; do
    PID=$(lsof -ti tcp:$PORT_NUM 2>/dev/null || true)
    if [ -n "$PID" ]; then
        echo "[CLEAN] Port $PORT_NUM in use (PID $PID) — stopping it..."
        kill -9 "$PID" 2>/dev/null || true
        sleep 1
    fi
done

# ── 7. Start Lab API ──────────────────────────────────────────────────────────
echo "[START] Starting Lab API backend (port 4100)..."
( cd "$LAB_API_DIR" && node server.js ) &
API_PID=$!
sleep 2

curl -sf http://localhost:4100/api/health > /dev/null || {
    echo "  ERROR: Lab API did not start. Check output above."
    kill "$API_PID" 2>/dev/null || true
    exit 1
}
echo "  Lab API is UP (PID: $API_PID)"

# ── 8. Start webapp ───────────────────────────────────────────────────────────
echo "[START] Starting Web Dashboard (port 3000)..."
( cd "$WEBAPP_DIR" && npm run dev ) &
WEB_PID=$!
sleep 5

# ── 9. Done ───────────────────────────────────────────────────────────────────
echo ""
echo "=========================================================="
echo "  VulnLab is RUNNING!"
echo ""
echo "  Open the dashboard: http://localhost:3000"
echo ""
echo "  Lab ports:"
echo "    DVWA        -> http://localhost:8088"
echo "    Juice Shop  -> http://localhost:3001"
echo "    WebGoat     -> http://localhost:8085"
echo "    bWAPP       -> http://localhost:8082"
echo "    phpMyAdmin  -> http://localhost:8084"
echo ""
echo "  Press Ctrl+C to stop all servers."
echo "=========================================================="
echo ""

# ── Wait / cleanup ────────────────────────────────────────────────────────────
trap 'echo ""; echo "Shutting down..."; kill "$API_PID" "$WEB_PID" 2>/dev/null || true; exit 0' INT TERM
wait "$API_PID"
