@echo off
setlocal enabledelayedexpansion

REM =============================================================================
REM setup.bat - VulnLab Quickstart for Windows (Command Prompt)
REM
REM Usage:
REM   Double-click setup.bat  OR  run from cmd:  setup.bat
REM =============================================================================

set "REPO_ROOT=%~dp0"
set "REPO_ROOT=%REPO_ROOT:~0,-1%"
set "LAB_API_DIR=%REPO_ROOT%\lab-api"
set "WEBAPP_DIR=%REPO_ROOT%\webapp"

echo.
echo ==========================================================
echo   VulnLab Quickstart - Setup
echo   Repo root: %REPO_ROOT%
echo ==========================================================
echo.

REM ── 1. Preflight checks ──────────────────────────────────────────────────────
echo [CHECK] Verifying prerequisites...
where node >nul 2>&1 || (echo   ERROR: Node.js not found. Install from https://nodejs.org && exit /b 1)
where npm  >nul 2>&1 || (echo   ERROR: npm not found. Install from https://nodejs.org && exit /b 1)
REM Check Docker status and create network
docker info >nul 2>&1
if !errorlevel! neq 0 (
    echo   ERROR: Docker is not running or not installed. Install Docker Desktop from https://docker.com && exit /b 1
)
echo   Docker is running.
docker network create lab_net >nul 2>&1

for /f "tokens=*" %%v in ('node --version') do echo   Node  : %%v
for /f "tokens=*" %%v in ('npm --version')  do echo   npm   : %%v
echo.

REM ── 2. lab-api/.env ──────────────────────────────────────────────────────────
if not exist "%LAB_API_DIR%\.env" (
    echo [SETUP] Creating lab-api\.env ...
    if exist "%LAB_API_DIR%\.env.example" (
        copy "%LAB_API_DIR%\.env.example" "%LAB_API_DIR%\.env" >nul
    ) else (
        (
            echo # Auto-generated by setup.bat
            echo PORT=4100
            echo LAB_DIR=
        ) > "%LAB_API_DIR%\.env"
    )
    echo   lab-api\.env created.
) else (
    echo [SETUP] lab-api\.env already exists - skipping.
)

REM ── 3. webapp/.env.local ─────────────────────────────────────────────────────
if not exist "%WEBAPP_DIR%\.env.local" (
    echo [SETUP] Creating webapp\.env.local ...
    (
        echo # Auto-generated by setup.bat
        echo NEXT_PUBLIC_LAB_API_URL=
        echo LAB_API_PORT=4100
    ) > "%WEBAPP_DIR%\.env.local"
    echo   webapp\.env.local created.
) else (
    echo [SETUP] webapp\.env.local already exists - skipping.
)
echo.

REM ── 4. npm install ───────────────────────────────────────────────────────────
echo [INSTALL] Installing lab-api dependencies...
pushd "%LAB_API_DIR%"
call npm install --silent
popd
echo   Done.

echo [INSTALL] Installing webapp dependencies...
pushd "%WEBAPP_DIR%"
call npm install --silent
popd
echo   Done.
echo.

REM ── 5. Docker containers ─────────────────────────────────────────────────────
echo [DOCKER] Starting all lab containers...
pushd "%REPO_ROOT%"
docker compose up -d
popd
echo   All containers started.
echo.

REM ── 6. Start Lab API in new window ───────────────────────────────────────────
echo [START] Starting Lab API backend (port 4100)...
start "VulnLab API" cmd /k "title VulnLab API [Port 4100] & cd /d "%LAB_API_DIR%" & node server.js"
timeout /t 3 /nobreak >nul

REM ── 7. Start webapp in new window ────────────────────────────────────────────
echo [START] Starting Web Dashboard (port 3000)...
start "VulnLab Dashboard" cmd /k "title VulnLab Dashboard [Port 3000] & cd /d "%WEBAPP_DIR%" & npm run dev"
timeout /t 5 /nobreak >nul

REM ── 8. Done ──────────────────────────────────────────────────────────────────
echo.
echo ==========================================================
echo   VulnLab is RUNNING!
echo.
echo   Open the dashboard: http://localhost:3000
echo.
echo   Lab ports:
echo     DVWA        -^> http://localhost:8088
echo     Juice Shop  -^> http://localhost:3001
echo     WebGoat     -^> http://localhost:8085
echo     bWAPP       -^> http://localhost:8082
echo     phpMyAdmin  -^> http://localhost:8084
echo.
echo   Two new windows have opened for the API and Dashboard.
echo   Close those windows to stop the servers.
echo ==========================================================
echo.
pause
